### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by c-johnson**
This PR removes dependencies causing security errors.

Dependencies removed include:
  - jest 
  - gulp-css64
  - gulp-inline

@gavinpatkinson It looks like the 'fonts' and 'inline' gulp tasks that invoked these dependencies were commented out, so I assume that they're not needed. Also jest; I couldn't find any tests anywhere, so hopefully okay to remove.

### CODE REVIEW

**Comment by gavinpatkinson** [comment]
LGTM, although you may want to double check fonts render correctly without local fonts and network fonts.

**Comment by c-johnson** [comment]
The fonts don't look exactly right...

image

Which is weird; we didn't actually change any functionality here, we just deleted a commented-out "fonts" task. Looks like this was commented out since last October.

Is it supposed to look like this?

**Comment by alexmatz** [comment]
yeah... font/typography looks off to me. @gavinpatkinson?

**Comment by gavinpatkinson** [comment]
Looks like you didn’t add the base64 encoded fonts to the css somewhere else

**Comment by c-johnson** [comment]
Ah, I was looking at the wrong output. When I consume this through wallet-generator it looks correct:

image

**Comment by c-johnson** [comment]
@gavinpatkinson I notice we're still using .ttf and .otf files in the /fonts directory though. Want me to swap these out for the base64 ones while I'm here? I assume they render the same.

**Comment by gavinpatkinson** [comment]
The affordance that base64 fonts provide is that they don't have to be separate files on a dir with the bundle, they can be inline css. This was ideal for Bridge and Wallet Generator because the index.html could be treated as an application the user can click on. So If that is still a requirement, base64 is probably the way to go.

**Comment by jyng** [comment]
@gavinpatkinson is this okay to merge?

**Comment by g-a-v-i-n** [comment]
Looks like only build deps were changed so LGTM.

**Pull request merged**
